from dotenv import load_dotenv
load_dotenv()

import streamlit as st
import time
import httpx
from datetime import datetime
from langchain_mistralai import ChatMistralAI
from graph.pipeline import run_all_evaluations, SUPPLIERS
from agents.planning_agent import load_or_generate_plan

st.set_page_config(
    page_title="CTTI Tender Evaluation — CTTI-2026-36",
    layout="wide"
)

# ── Session state initialisation ──────────────────────────────────────────────

if "plan" not in st.session_state:
    with st.spinner("Loading evaluation plan..."):
        st.session_state.plan = load_or_generate_plan()

if "results" not in st.session_state:
    st.session_state.results = None

if "audit_log" not in st.session_state:
    st.session_state.audit_log = []

if "submitted" not in st.session_state:
    st.session_state.submitted = False

# ── Comparison helper ─────────────────────────────────────────────────────────

_comparison_llm = ChatMistralAI(model="mistral-large-latest", temperature=0)


def get_comparison(criterion_id: str, criterion_name: str, results: dict) -> str:
    cache_key = f"comparison_{criterion_id}"
    if cache_key in st.session_state:
        return st.session_state[cache_key]

    prompt = f"""You are summarising how three suppliers compare on a single evaluation criterion for a procurement officer at CTTI.

Criterion: {criterion_name}

Supplier A ({SUPPLIERS[0]['name']}):
{results[SUPPLIERS[0]['id']][criterion_id]['evidence']}

Supplier B ({SUPPLIERS[1]['name']}):
{results[SUPPLIERS[1]['id']][criterion_id]['evidence']}

Supplier C ({SUPPLIERS[2]['name']}):
{results[SUPPLIERS[2]['id']][criterion_id]['evidence']}

Write 3 bullet points — one per supplier — comparing their relative strengths and weaknesses on this criterion.
Be concise. Do not recommend a winner.
Maximum 2 sentences per bullet.
"""
    text = "Comparison temporarily unavailable."
    for attempt in range(5):
        try:
            response = _comparison_llm.invoke([{"role": "user", "content": prompt}])
            text = response.content
            break
        except httpx.HTTPStatusError as exc:
            if exc.response.status_code == 429 and attempt < 4:
                time.sleep(30 * (attempt + 1))
            else:
                break
        except Exception:
            break

    st.session_state[cache_key] = text
    return text


# ── Tabs ──────────────────────────────────────────────────────────────────────

tab1, tab2 = st.tabs(["📊 Evaluation Dashboard", "📝 Audit Log"])

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 1 — EVALUATION DASHBOARD
# ═══════════════════════════════════════════════════════════════════════════════

with tab1:
    st.title("Tender Evaluation Workbench")
    st.caption(
        "CTTI-2026-36 · Quantum Key Distribution Infrastructure · "
        "Internal use only — Mesa de Contractació"
    )

    st.markdown("**Suppliers loaded:**")
    for supplier in SUPPLIERS:
        st.markdown(f"✓ {supplier['name']}")

    st.divider()

    # ── STEP 1 — Plan review ──────────────────────────────────────────────────

    plan = st.session_state.plan

    st.subheader("📋 Evaluation Plan")
    st.caption(
        f"Generated by Planning Agent — "
        f"{plan['generated_at'][:10]} — "
        f"Contract {plan['contract_id']}"
    )

    for criterion in plan["criteria"]:
        if criterion["has_subcriteria"]:
            st.markdown(f"**{criterion['name']}** — {criterion['max_points']} pts total")
            table_rows = [
                {"Sub-criterion": sc["name"], "Points": sc["points"]}
                for sc in criterion["subcriteria"]
            ]
            st.dataframe(table_rows, use_container_width=True, hide_index=True)
        else:
            st.markdown(
                f"**{criterion['name']}** — {criterion['max_points']} pts · "
                f"Single evaluation — no sub-criteria"
            )

    st.info(
        "Review the evaluation plan above. "
        "It was generated by the Planning Agent reading the PCAP document. "
        "Click Confirm to proceed."
    )

    confirm_button = st.button(
        "✅ Confirm Plan and Run Evaluation",
        type="primary",
        disabled=st.session_state.results is not None,
    )

    if confirm_button:
        with st.spinner("Agent evaluating all suppliers and criteria..."):
            st.session_state.results = run_all_evaluations(plan)
        st.rerun()

    if st.session_state.results is None:
        st.stop()

    # ── STEP 2 — Evaluation grid ──────────────────────────────────────────────

    results = st.session_state.results

    st.subheader("Evaluation Grid")
    st.caption(
        "Read the AI-surfaced evidence for each cell. "
        "Assign your score independently. "
        "AI output is advisory only."
    )

    for criterion in plan["criteria"]:
        st.markdown("---")

        if criterion["has_subcriteria"]:
            st.markdown(
                f"### {criterion['name']} "
                f"({criterion['max_points']} pts total)"
            )
            st.caption(
                f"{len(criterion['subcriteria'])} sub-criteria identified by Planning Agent"
            )

            for sc in criterion["subcriteria"]:
                st.markdown(f"**{sc['name']} — {sc['points']} pts**")
                cols = st.columns(3)

                for supplier, col in zip(SUPPLIERS, cols):
                    with col:
                        result = (
                            results[supplier["id"]][criterion["id"]]["subcriteria"][sc["id"]]
                        )
                        st.markdown(f"**{supplier['name']}**")
                        with st.container(border=True):
                            st.markdown("🟡 **AI-GENERATED — Review required**")
                            st.markdown(f"*\"{result['evidence']}\"*")
                            st.divider()
                            st.caption(f"⚠️ {result['agent_note']}")

                        st.number_input(
                            label=f"Score (0–{sc['points']})",
                            min_value=0.0,
                            max_value=float(sc["points"]),
                            value=0.0,
                            step=0.5,
                            key=f"score_{supplier['id']}_{criterion['id']}_{sc['id']}",
                        )

            st.markdown("**Sub-totals for this criterion:**")
            subtotal_cols = st.columns(3)
            for supplier, col in zip(SUPPLIERS, subtotal_cols):
                with col:
                    subtotal = sum(
                        st.session_state.get(
                            f"score_{supplier['id']}_{criterion['id']}_{sc['id']}", 0.0
                        )
                        for sc in criterion["subcriteria"]
                    )
                    st.metric(
                        label=supplier["name"],
                        value=f"{subtotal:.1f} / {criterion['max_points']}",
                    )

        else:
            criterion_name = results[SUPPLIERS[0]["id"]][criterion["id"]]["criterion_name"]
            st.markdown(f"### {criterion_name}")

            for supplier in SUPPLIERS:
                result = results[supplier["id"]][criterion["id"]]
                max_points = result["max_points"]

                st.markdown(f"**{supplier['name']}**")
                st.caption(f"{criterion_name} · max {max_points} pts")
                st.markdown("🟡 **AI-GENERATED — Human review required**")

                with st.container(border=True):
                    st.markdown(f"*\"{result['evidence']}\"*")
                    st.divider()
                    st.caption(f"⚠️ {result['agent_note']}")

                st.number_input(
                    label=f"Score (0–{max_points})",
                    min_value=0.0,
                    max_value=float(max_points),
                    value=0.0,
                    step=0.5,
                    key=f"score_{supplier['id']}_{criterion['id']}",
                )

            all_scored_for_criterion = True
            cache_key = f"comparison_{criterion['id']}"
            if all_scored_for_criterion:
                if cache_key not in st.session_state:
                    with st.spinner(f"Generating comparison for {criterion_name}..."):
                        get_comparison(criterion["id"], criterion_name, results)
                comparison_text = st.session_state.get(cache_key, "")
                if comparison_text:
                    st.markdown("---")
                    st.markdown("📊 **Cross-supplier comparison**")
                    with st.container(border=True):
                        st.markdown(comparison_text)

    # ── Results summary table ─────────────────────────────────────────────────

    st.divider()
    st.subheader("Evaluation Summary")

    table_data = []
    leading_supplier = None
    highest_total = -1

    for supplier in SUPPLIERS:
        row = {"Supplier": supplier["name"]}
        total = 0.0
        for criterion in plan["criteria"]:
            if criterion["has_subcriteria"]:
                criterion_score = sum(
                    st.session_state.get(
                        f"score_{supplier['id']}_{criterion['id']}_{sc['id']}", 0.0
                    )
                    for sc in criterion["subcriteria"]
                )
            else:
                criterion_score = st.session_state.get(
                    f"score_{supplier['id']}_{criterion['id']}", 0.0
                )
            row[criterion["id"]] = criterion_score
            total += criterion_score
        row["Total"] = round(total, 1)
        table_data.append(row)

        if total > highest_total:
            highest_total = total
            leading_supplier = supplier["name"]

    max_total = sum(c["max_points"] for c in plan["criteria"])
    st.dataframe(table_data, use_container_width=True)
    st.success(
        f"Highest scoring supplier: {leading_supplier} "
        f"with {highest_total:.1f} / {max_total:.0f} points"
    )
    st.caption(
        "Automatic criteria (Sobre C, 51 points) are evaluated separately "
        "using the price formula from PCAP Annex 2.b. "
        "Final ranking requires combining both scores."
    )

    # ── Sign and submit ───────────────────────────────────────────────────────

    st.divider()
    st.subheader("Sign and Submit Evaluation")

    evaluator_id = st.text_input(
        "Evaluator ID",
        placeholder="e.g. david.ferrer.ctti",
    )

    st.caption(
        "By submitting you confirm that you have independently reviewed all "
        "AI-generated evidence and assigned scores based on your own "
        "professional judgment. Law 40/2015 Art. 24."
    )

    submit_button = st.button(
        "✅ Sign and Submit Evaluation",
        type="primary",
        disabled=not evaluator_id or st.session_state.submitted,
    )

    if submit_button and evaluator_id:
        scores_record = {}
        evidence_record = {}

        for supplier in SUPPLIERS:
            scores_record[supplier["id"]] = {}
            evidence_record[supplier["id"]] = {}

            for criterion in plan["criteria"]:
                if criterion["has_subcriteria"]:
                    scores_record[supplier["id"]][criterion["id"]] = {
                        sc["id"]: st.session_state.get(
                            f"score_{supplier['id']}_{criterion['id']}_{sc['id']}", 0.0
                        )
                        for sc in criterion["subcriteria"]
                    }
                    evidence_record[supplier["id"]][criterion["id"]] = {
                        "criterion_name": criterion["name"],
                        "max_points": criterion["max_points"],
                        "subcriteria": {
                            sc["id"]: {
                                "name": sc["name"],
                                "points": sc["points"],
                                "evidence_surfaced": results[supplier["id"]][criterion["id"]]["subcriteria"][sc["id"]]["evidence"],
                                "agent_note": results[supplier["id"]][criterion["id"]]["subcriteria"][sc["id"]]["agent_note"],
                            }
                            for sc in criterion["subcriteria"]
                        },
                    }
                else:
                    scores_record[supplier["id"]][criterion["id"]] = st.session_state.get(
                        f"score_{supplier['id']}_{criterion['id']}", 0.0
                    )
                    r = results[supplier["id"]][criterion["id"]]
                    evidence_record[supplier["id"]][criterion["id"]] = {
                        "criterion_name": r["criterion_name"],
                        "max_points": r["max_points"],
                        "evidence_surfaced": r["evidence"],
                        "agent_note": r["agent_note"],
                    }

        audit_entry = {
            "evaluator_id": evaluator_id,
            "timestamp": datetime.now().isoformat(),
            "contract": "CTTI-2026-36",
            "regulatory_note": (
                "Law 40/2015 Art. 24 — evaluator signature recorded. "
                "EU AI Act Annex III — human review completed prior "
                "to all scoring decisions."
            ),
            "scores": scores_record,
            "evidence": evidence_record,
        }
        st.session_state.audit_log.append(audit_entry)
        st.session_state.submitted = True
        st.success("Evaluation submitted. Audit record created.")

# ═══════════════════════════════════════════════════════════════════════════════
# TAB 2 — AUDIT LOG
# ═══════════════════════════════════════════════════════════════════════════════

with tab2:
    st.title("Audit Log")
    st.caption(
        "Complete record of agent actions and human decisions. "
        "Law 40/2015 Art. 24 — EU AI Act Annex III."
    )

    if not st.session_state.audit_log:
        st.info(
            "No submissions yet. Complete the evaluation in Tab 1 "
            "and submit to generate the audit record."
        )
    else:
        for entry in st.session_state.audit_log:
            st.markdown(f"**Submitted by:** {entry['evaluator_id']}")
            st.markdown(f"**Timestamp:** {entry['timestamp']}")
            st.markdown(f"**Contract:** {entry['contract']}")
            st.markdown(f"**Regulatory note:** {entry['regulatory_note']}")

            st.markdown("**Scores recorded:**")
            table_data = []
            for supplier in SUPPLIERS:
                row = {"Supplier": supplier["name"]}
                total = 0.0
                for criterion in plan["criteria"]:
                    raw = entry["scores"][supplier["id"]][criterion["id"]]
                    if isinstance(raw, dict):
                        score = sum(raw.values())
                    else:
                        score = raw or 0.0
                    row[criterion["id"]] = score
                    total += score
                row["Total"] = round(total, 1)
                table_data.append(row)
            st.dataframe(table_data, use_container_width=True)

            st.markdown("**Agent evidence on record:**")
            for supplier in SUPPLIERS:
                with st.expander(supplier["name"]):
                    for criterion in plan["criteria"]:
                        ev = entry["evidence"][supplier["id"]][criterion["id"]]
                        st.markdown(
                            f"**{ev['criterion_name']}** "
                            f"(max {ev['max_points']} pts)"
                        )
                        if "subcriteria" in ev:
                            for sc_id, sc_ev in ev["subcriteria"].items():
                                st.markdown(f"*{sc_ev['name']} ({sc_ev['points']} pts)*")
                                st.markdown(f"Evidence: {sc_ev['evidence_surfaced']}")
                                st.markdown(f"Agent note: {sc_ev['agent_note']}")
                                st.divider()
                        else:
                            st.markdown(f"*Evidence surfaced:* {ev['evidence_surfaced']}")
                            st.markdown(f"*Agent note:* {ev['agent_note']}")
                            st.divider()
